required-players: 1
countdown-seconds: 5
lobby-spawn:
  world: "world"
  x: -9.035
  y: -60
  z: 57.239
  yaw: -100
  pitch: 0
block-breakers-lobby:
  world: 'block'
  x: 213.916
  y: 261
  z: 163.605
  yaw: 60
  pitch: 60
arenas:
  0:
    world: 'block'
    x: 225.564
    y: 261
    z: 165.3
    pitch: 60
    yaw: 60
  1:
    world: 'platform'
    x: 100
    y: 100
    z: 100
    pitch: 60
    yaw: 60

