requirde-players: 2
countdown-seconds: 3
lobby-spawn:
  world: 'world'
  x: 164.5
  y: 71.5
  z: -3.5
  yaw: -100
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 164.5
    y: 71.5
    z: -3.5
    yaw: -100
    pitch: 0
  1:
    world: 'world'
    x: 164.5
    y: 71.5
    z: -3.5
    yaw: -100
    pitch: 0

