required-players: 1
countdown-seconds: 5
lobby-spawn:
  world: "world"
  x: 164.5
  y: 71.5
  z: -3.5
  yaw: -100
  pitch: 0
arenas:
  0:
    world: 'world'
    x: -66.918
    y: 63
    z: -36.113
    pitch: 60
    yaw: 60
  1:
    world: 'world'
    x: 100
    y: 100
    z: 100
    pitch: 60
    yaw: 60

