required-players: 1
countdown-seconds: 5
lobby-spawn:
  world: "world"
  x: -9.035
  y: -60
  z: 57.239
  yaw: -100
  pitch: 0
block-breakers-lobby:
  world: 'world'
  x: -239.7
  y: -60
  z: -28.3
  yaw: 60
  pitch: 60
arenas:
  0:
    world: 'world'
    x: -237.335
    y: -60
    z: -64.796
    pitch: 60
    yaw: 60
  1:
    world: 'world'
    x: 100
    y: 100
    z: 100
    pitch: 60
    yaw: 60

